name: fitriuas_final
description: "CafeCup - Your Perfect Coffee Experience"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
#  http: ^1.1.0
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  pocketbase: ^0.18.0
  provider: ^6.1.1
  intl: ^0.18.0
  webview_flutter: ^4.8.0  # Untuk menampilkan halaman Snap Midtrans
  http: ^1.2.2  # Untuk komunikasi dengan backend
  midtrans_sdk: ^0.4.0
path: ../midtrans_sdk_fork


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/your_image.png

  # To add custom fonts, use the fonts section below:
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-Bold.ttf
  #         weight: 700
